-- =====================================================================
--  SISTEMA DE CAJAS · 07 · FACILITO COMPLETO
--
--  Dos cosas nuevas:
--   1. Los 880 productos de Facilito con la comisión que la plataforma
--      te reconoce por cada uno (porcentaje o valor fijo).
--   2. La escalera de precios de recarga: dado el valor que muestra la
--      plataforma, cuánto se le cobra al cliente.
--
--  Con eso, registrar una recarga es elegir el producto y escribir el
--  valor: el sistema calcula el cobro, las dos comisiones y los saldos.
--
--  Ejecutar después de 06_comisiones.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- PRODUCTOS
-- El nombre es el que sale en el comprobante ("MRF - TUENTI - PAQ.").
-- ---------------------------------------------------------------------
create table if not exists productos_facilito (
  id             bigint generated always as identity primary key,
  nombre         text not null unique,
  familia        text not null,              -- MRF · MSP · MTD · TRINITY
  categoria      text,                       -- AGUA, LUZ, COLOMBIA...
  tipo           text not null check (tipo in ('recarga','juego','servicio')),
  comision_tipo  text not null check (comision_tipo in ('porcentual','fija')),
  comision_valor numeric(12,4) not null,     -- % o $ según comision_tipo
  activo         boolean not null default true
);

create index if not exists productos_busqueda on productos_facilito (tipo, nombre);

comment on table productos_facilito is
  'Comisión que Facilito TE RECONOCE por producto. Es ingreso, no costo.';

-- ---------------------------------------------------------------------
-- PRECIOS DE RECARGA
-- Qué se le cobra al cliente según el valor que muestra la plataforma.
-- Cada fila puede resolverse de tres formas, y gana la de mayor prioridad:
--   precio_fijo   -> se cobra ese total exacto
--   recargo_fijo  -> se cobra el valor más ese recargo
--   redondeo      -> se sube al siguiente múltiplo (2,15 -> 2,50)
-- ---------------------------------------------------------------------
create table if not exists precios_recarga (
  id            bigint generated always as identity primary key,
  monto_desde   numeric(14,4) not null,
  monto_hasta   numeric(14,4),              -- null = sin tope
  precio_fijo   numeric(14,4),
  recargo_fijo  numeric(14,4),
  redondeo      numeric(14,4),
  prioridad     smallint not null default 5, -- mayor gana
  vigente_desde date not null default current_date,
  vigente_hasta date,
  notas         text,
  constraint precio_una_regla check (
    (precio_fijo  is not null)::int
  + (recargo_fijo is not null)::int
  + (redondeo     is not null)::int = 1
  )
);

delete from precios_recarga;

insert into precios_recarga (monto_desde, monto_hasta, precio_fijo, recargo_fijo,
                             redondeo, prioridad, notas) values
  -- Tramos exactos de la tabla del local (ganan sobre la regla general)
  (1.00, 1.00, 1.10, null, null, 10, 'Recarga de $1'),
  (1.50, 1.50, 2.00, null, null, 10, 'Recarga de $1,50'),
  (2.00, 2.10, 2.20, null, null, 10, 'Recargas de 2 · 2,05 · 2,10'),
  (3.00, 3.20, 3.50, null, null, 10, 'Recargas de 3 · 3,05 · 3,10 · 3,15 · 3,20'),
  (3.50, 3.50, 4.00, null, null, 10, 'Recarga de 3,50'),
  (4.00, 4.30, 4.50, null, null, 10, 'Recargas de 4 hasta 4,30'),
  -- Regla general para todo lo demás
  (0.01, 4.9999, null, null, 0.50,  5, 'Sube al siguiente múltiplo de $0,50'),
  (5.00, null,   null, 0.50, null,  5, 'Desde $5: comisión física de $0,50');

-- ---------------------------------------------------------------------
-- PRECIO DE UNA RECARGA
-- Devuelve el TOTAL que se le cobra al cliente.
-- ---------------------------------------------------------------------
create or replace function precio_recarga(p_monto numeric)
returns numeric
language plpgsql
stable
as $$
declare
  r precios_recarga;
begin
  select * into r
  from precios_recarga
  where p_monto >= monto_desde
    and (monto_hasta is null or p_monto <= monto_hasta)
    and vigente_desde <= current_date
    and (vigente_hasta is null or vigente_hasta >= current_date)
  order by prioridad desc, monto_desde desc
  limit 1;

  if not found then
    return round(p_monto, 2);
  end if;

  if r.precio_fijo is not null then
    return r.precio_fijo;
  elsif r.recargo_fijo is not null then
    return round(p_monto + r.recargo_fijo, 2);
  else
    -- siguiente múltiplo ESTRICTAMENTE mayor: 2,15 -> 2,50 y 2,50 -> 3,00
    return round(floor(p_monto / r.redondeo) * r.redondeo + r.redondeo, 2);
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- TODO EL CÁLCULO DE UN MOVIMIENTO DE FACILITO, EN UNA SOLA LLAMADA
-- La pantalla solo dice qué producto y qué valor; esto devuelve lo demás.
-- ---------------------------------------------------------------------
create or replace function calcular_facilito(p_producto bigint, p_monto numeric)
returns table (
  producto_tipo    text,
  total_cobrar     numeric,
  comision_local   numeric,
  comision_prov    numeric,
  ganancia         numeric
)
language plpgsql
stable
as $$
declare
  pr   productos_facilito;
  caja smallint;
  tot  numeric(14,4);
  loc  numeric(14,4);
  prov numeric(14,4);
begin
  select * into pr from productos_facilito where id = p_producto;
  if not found then
    raise exception 'El producto % no existe.', p_producto;
  end if;

  select cj.id into caja from cajas cj where cj.tipo = 'facilito' limit 1;

  -- Lo que el proveedor te reconoce
  if pr.comision_tipo = 'porcentual' then
    prov := round(p_monto * pr.comision_valor / 100, 4);
  else
    prov := pr.comision_valor;
  end if;

  -- Lo que le cobras al cliente
  if pr.tipo = 'recarga' then
    tot := precio_recarga(p_monto);
    loc := round(tot - p_monto, 4);
  else
    loc := coalesce(buscar_tarifa(caja, 'local', 'servicio', null, p_monto), 0);
    tot := round(p_monto + loc, 4);
  end if;

  return query select pr.tipo, tot, loc, prov, round(loc + prov, 4);
end;
$$;

grant select on productos_facilito, precios_recarga to authenticated;
grant execute on function precio_recarga(numeric)              to authenticated;
grant execute on function calcular_facilito(bigint, numeric)   to authenticated;

alter table productos_facilito enable row level security;
alter table precios_recarga    enable row level security;
drop policy if exists "leer productos" on productos_facilito;
drop policy if exists "leer precios"   on precios_recarga;
drop policy if exists "editar precios" on precios_recarga;
create policy "leer productos" on productos_facilito for select to authenticated using (true);
create policy "leer precios"   on precios_recarga    for select to authenticated using (true);
create policy "editar precios" on precios_recarga    for all    to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------
-- LOS 880 PRODUCTOS
-- ---------------------------------------------------------------------
insert into productos_facilito (nombre, familia, categoria, tipo, comision_tipo, comision_valor) values
  ('MRF - AKIMOVIL', 'MRF', 'AKIMOVIL', 'recarga', 'porcentual', 4.5000),
  ('MRF - AKIMOVIL - PAQ', 'MRF', 'AKIMOVIL', 'recarga', 'porcentual', 4.5000),
  ('MRF - CLARO', 'MRF', 'CLARO', 'recarga', 'porcentual', 0.0000),
  ('MRF - CLARO - MEGAS', 'MRF', 'CLARO', 'recarga', 'porcentual', 5.0000),
  ('MRF - CLARO - PAQ.', 'MRF', 'CLARO', 'recarga', 'porcentual', 5.0000),
  ('MRF - CNT', 'MRF', 'CNT', 'recarga', 'porcentual', 6.0000),
  ('MRF - CNT - PAQ.', 'MRF', 'CNT', 'recarga', 'porcentual', 6.0000),
  ('MRF - CNT - WIFI', 'MRF', 'CNT', 'recarga', 'porcentual', 3.5000),
  ('MRF - CNT TV PREPAGO', 'MRF', 'CNT TV PREPAGO', 'recarga', 'porcentual', 3.5000),
  ('MRF - DIRECTV', 'MRF', 'DIRECTV', 'recarga', 'porcentual', 3.5000),
  ('MRF - MAXIPLUS', 'MRF', 'MAXIPLUS', 'recarga', 'porcentual', 4.5000),
  ('MRF - MAXIPLUS - PAQ', 'MRF', 'MAXIPLUS', 'recarga', 'porcentual', 4.5000),
  ('MRF - MOVISTAR', 'MRF', 'MOVISTAR', 'recarga', 'porcentual', 4.5000),
  ('MRF - MOVISTAR - PAQ.', 'MRF', 'MOVISTAR', 'recarga', 'porcentual', 4.5000),
  ('MRF - TUENTI', 'MRF', 'TUENTI', 'recarga', 'porcentual', 4.5000),
  ('MRF - TUENTI - PAQ.', 'MRF', 'TUENTI', 'recarga', 'porcentual', 4.5000),
  ('MSP - AGUA - AGUA DE MILAGRO - EPAMIL - ABONO 2', 'MSP', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MSP - AGUA - AGUAS DE CHUNO (CHONE)', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - AGUAS DE JIPIJAPA', 'MSP', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MSP - AGUA - AMAGUA - FACTURAS DE VENTA AMAGUA', 'MSP', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MSP - AGUA - EMAAP - QUITO - ABONO 2', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - EMAPA DAULE', 'MSP', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MSP - AGUA - EMAPA-AMBATO - ABONO 2', 'MSP', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MSP - AGUA - EMAPA-I IBARRA - ABONO 2', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - EMAPAD EP DURAN', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - EMASA - AGUAS DE PEDRO MONCAYO - ABONO 2', 'MSP', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MSP - AGUA - EMPRESA PUBLICA DEL AGUA EPA EP', 'MSP', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MSP - AGUA - EPAM MANTA', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - EPMAPAQ QUEVEDO', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - INTERAGUA CUPONES', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - PORTOAGUAS EPMAPAP', 'MSP', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MSP - AGUA - RUMIÑAHUI', 'MSP', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MSP - AGUAS  - TOSAGUA - SAN VICENTE - BOLIVAR - SUCRE - JUNIN - EMMAP EP', 'MSP', 'AGUAS ', 'servicio', 'fija', 0.1000),
  ('MSP - CATALOGO - HERBALIFE DEL ECUADOR', 'MSP', 'CATALOGO', 'servicio', 'fija', 0.1000),
  ('MSP - CATALOGO - LILE', 'MSP', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MSP - CATALOGO - YANBAL', 'MSP', 'CATALOGO', 'servicio', 'fija', 0.1000),
  ('MSP - CNT - TELEFONIA FIJA - ABONO 2', 'MSP', 'CNT', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - ACEPTACIONES S A ACCEPTANCE', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - AUTOMOTORES Y ANEXOS AYASA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - BANCO AMIBANK (FINCA)', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1500),
  ('MSP - CREDITO - BANCO CODESARROLLO', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - BANCO COMERCIAL MANABI', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - BANCO DMIRO', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1500),
  ('MSP - CREDITO - BANCO PROCREDIT', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - BANCO SOLIDARIO', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1500),
  ('MSP - CREDITO - CARTERA ARS PERUZZI', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - CEBI', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - CHEVYPLAN', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COAC MANANTIAL DE ORO LTDA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COBRA FACIL RECOVER', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA CREDICEL', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA GESTIONA GTX', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA GESTIONA TARJETA CREDITO', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA KOLVECH TELECOMVAS', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA LIDERCORAZ', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1500),
  ('MSP - CREDITO - COBRANZA NOVACREDIT SA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COBRANZA PRACTUM', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - CONSORCIO COBRANZA ESMERALDAS', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - CONSORCIO DEL PICHINCHA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1500),
  ('MSP - CREDITO - COOP SAN FRANCISCO DE ASIS', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COOP. PISA LTDA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COOPERATIVA AHORRO CREDITO COOPCENTRO', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COOPERATIVA ATUNTAQUI', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - COOPERATIVA PABLO MUÑOZ VEGA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - COOPERATIVA TULCAN', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - CREDIPRIME', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - FINANMOTORS', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - FUNDACION FACES', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - GEONET - CONSULTIM Cobranzas', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - GEONET - MARVICNET Cobranzas', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - GRAN HOGAR', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - INSOTEC', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - MULTA CHEQUES PROTESTOS', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - MULTICOMERCIO MOLINA Y ORTEGA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - MUTUALISTA IMBABURA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - MUTUALISTA PICHINCHA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - ORIGINARSA S. A.', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - SICCEC CIA LTDA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - SICONTAC CENTER', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - CREDITO - SUKASA', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MSP - CREDITO - TODOHOGAR', 'MSP', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MSP - DEPOSITO - BANCO COMERCIAL MANABI CTA AHORROS', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - BANCO COMERCIAL MANABI CTA CORRIENTE', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - BANCO DE LOJA', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - BANCO GENERAL RUMIÑAHUI', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - BANCO PROCREDIT S.A.', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - COOPERATIVA ALIANZA DEL VALLE', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1700),
  ('MSP - DEPOSITO - COOPERATIVA ANDALUCIA', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - COOPERATIVA ATUNTAQUI', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - COOPERATIVA CCP - CONSTRUCCION COMERCIO PRODUCCION', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1700),
  ('MSP - DEPOSITO - COOPERATIVA COOPROGRESO', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - COOPERATIVA OSCUS', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - COOPERATIVA PABLO MUÑOZ VEGA', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1700),
  ('MSP - DEPOSITO - COOPERATIVA SAN FRANCISCO LTDA', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1000),
  ('MSP - DEPOSITO - COOPERATIVA TULCAN', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - DEPOSITO - MUTUALISTA PICHINCHA', 'MSP', 'DEPOSITO', 'servicio', 'fija', 0.1500),
  ('MSP - ETAPA CUENCA - VARIOS (Internet,Telefonia fija,TV, etc)', 'MSP', 'ETAPA CUENCA', 'servicio', 'fija', 0.1700),
  ('MSP - IESS - VOLUNTARIO', 'MSP', 'IESS', 'servicio', 'fija', 0.1700),
  ('MSP - JARDINES DE GUAYAQUIL S.A.', 'MSP', 'JARDINES DE GUAYAQUIL S.A.', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CENTROSUR AZUAY - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MSP - LUZ - CNEL BOLIVAR - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL EL ORO - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL ESMERALDAS - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL GUAYAQUIL - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL GUAYAS LOS RIOS - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL LOS RIOS - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL MANABI - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL MILAGRO - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL SANTA ELENA - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - CNEL SANTO DOMINGO - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - EEASA TUNGURAHUA', 'MSP', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MSP - LUZ - EEQ QUITO - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MSP - LUZ - EERSA CHIMBORAZO', 'MSP', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MSP - LUZ - EMELNORTE (IMBABURA-CARCHI-CAYAMBE) - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1500),
  ('MSP - LUZ - EMPRESA ELECTRICA LOJA', 'MSP', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MSP - LUZ - MEER - ELECTRICA AZOGUES - ABONO 2', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - MEER - ELECTRICA COTOPAXI', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - LUZ - MEER - ELECTRICA GALAPAGOS', 'MSP', 'LUZ', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ACADEMIA PRINCESA DE GALES NORTE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ACADEMIA PRINCESA DE GALES QUITO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ALGAR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ASO PADRES FAM COLEGIO FARINA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CAP RAFAEL MORAN VALVERDE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CEI EL MUNDO DE MOZART', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CEI KINDERGARDEN CANGURITOS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CEI SAN MATEO CATALINA LOGRONO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CENTRO EDUCATIVO JEAN PIAGET', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CENTRO EDUCATIVO LETORT', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CENTRO EDUCATIVO LOS PINOS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CENTRO INFANTIL ENTRE LIBROS Y GARABATOS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - COB CENTRO EDUC BILINGUE GRANJA CEBLAG', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COBR UNI EDU FEDERICO GONZALEZ SUAREZ', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COBRANZA INNOVA SCHOOLS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COL PART RELIG. MARIA NAZARETH', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO FRANCISCA DE LAS LLAGAS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO GEORGE WASHINGTON', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO LA PRESENTACIÓN', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO PARTICULAR LOS ILINIZAS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO ROSARIO DEL ALCAZAR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO SANCHEZ Y CIFUENTES SOCIEDAD', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - COLEGIO SANTA MARIA EUFRASIA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - COVIMA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - CTT DE LOS ANDES', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - DELIA INES OLIVO ARRIETA - PENSIONADO OLIVO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - EFI CORDILLERA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - EL PRADO LEARNING', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ESC PARTICULAR SANTA LUISA MARILLAC', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ESCUELA ANGEL DE LA GUARDA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ESCUELA JULIA NAVARRETE MENDOZA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ESCUELA PABLO BAQUERIZO NAZUR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - ESPOL TECH', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - GUARDERIA INFANTIL MI PEQUENO MUNDO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - HER DOMINI INMACULADA CONCEPCION CUENCA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - IBEC ECUADOR CETIDE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - INST. SUP. TEC. CORDILLERA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MSP - MATRICULAS Y PENSIONES - INSTITUTO DE SCHOENSTATT', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - INSTITUTO SUDAMERICANO INTESUD', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - INSTITUTO SUPERARSE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - JARDIN DE INFANTES PEPE Y MARY', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - LICEO DE LOS ANDES', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - MARTIMCERERE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - MATRIX TRAINING CENTER', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - TRANSPORTE COL ABDON CALDERON', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - TRANSPORTE COLEGIO RUMIPAMBA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - TRANSPORTE ESCOLAR 9 DE JUNIO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - TRANSPORTE ESCUELA GUAYAQUIL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UDA UNIVERSIDAD DEL AZUAY', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE ALBORADA MILAGRO UNEDALB SAS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE ALFG VICTOR NARANJO FIALLO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE AMERICA DEL SUR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE ARMADA NACIONAL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE CAPITAN GIOVANNI CALLES', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE CIUDAD DE OTAVALO UECO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE COMBATIENTES DE TAPI', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE DR MANUEL AGUSTIN AGUIRRE RIOS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE EUGENIO ESPEJO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE FFAA COMIL 3 HEROES DEL 41', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE GALILEO GALILEI', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE HERMANO MIGUEL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE HEROES DEL CENEPA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE JOSE DE VILLAMIL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE JUAN LEON MERA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE JULIO MARIA MATOVELLE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE MIGUEL ITURRALDE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE MUNDO AMERICA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE PARTICULAR AGUSTIN CUEVA TAMARIZ', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE PARTICULAR LOS DELFINES', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE PATRIA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE SAN FELIPE NERI', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE TENIENTE HUGO ORTIZ', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE VALM. MANUEL NIETO CADENA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UE VIGOTSKY RIOBAMBA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UIDE UNIVERSIDAD INTERNACIONAL EC', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UK SCHOOL UNIKIDS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD ED. EXPERIMENTAL EC SUIZO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA ABDON CALDERON', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA ASUNCION', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA COMPUTER WORLD', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA FAE 1', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA FAE 2', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA FAE 3 TAURA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA FAE 5', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA GUAYAS', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA LA INMACULADA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA MUNDIAL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA MUNDIAL - EDUMIGAR S.A.', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA NUEVA AMERICA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA SAN PIO X', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA TACL', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIDAD EDUCATIVA TCRN LAURO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIV IBEROAMERICANA DEL ECUADOR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD ANDINA SIMON BOLIVAR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD CENTRAL DEL ECUADOR', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD DE CHIMBORAZO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD DE LOS ANDES (UNIANDES)', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD DE OTAVALO', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD METROPOLITANA UMET', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UNIVERSIDAD TECNOLOGICA INDOAMERICA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MSP - MATRICULAS Y PENSIONES - UTI NUEVOS ESTUDIANTES', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - UTPL UNIVERSIDAD TECNICA PARTICULAR LOJA', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MATRICULAS Y PENSIONES - WILLIAM CAXTON COLLEGE', 'MSP', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1000),
  ('MSP - MOVISTAR - PLAN POSTPAGO PA', 'MSP', 'MOVISTAR', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO - GAD RIOBAMBA INFRACCIONES', 'MSP', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO - GAD RIOBAMBA MATRICULACION', 'MSP', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO - SANTA CRUZ', 'MSP', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE AMBATO - VARIOS', 'MSP', 'MUNICIPIO DE AMBATO', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE CHONE - VARIOS', 'MSP', 'MUNICIPIO DE CHONE', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE DURAN', 'MSP', 'MUNICIPIO DE DURAN', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE GUAYAQUIL - MI LOTE.', 'MSP', 'MUNICIPIO DE GUAYAQUIL', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE GUAYAQUIL - PREDIOS', 'MSP', 'MUNICIPIO DE GUAYAQUIL', 'servicio', 'fija', 0.1500),
  ('MSP - MUNICIPIO DE IBARRA - VARIOS', 'MSP', 'MUNICIPIO DE IBARRA', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE MANTA - VARIOS', 'MSP', 'MUNICIPIO DE MANTA', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE MEJIA - OTROS RUBROS', 'MSP', 'MUNICIPIO DE MEJIA', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE MEJIA - PREDIOS', 'MSP', 'MUNICIPIO DE MEJIA', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE MILAGRO - VARIOS', 'MSP', 'MUNICIPIO DE MILAGRO', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE PORTOVIEJO - VARIOS', 'MSP', 'MUNICIPIO DE PORTOVIEJO', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIO DE QUEVEDO PREDIOS', 'MSP', 'MUNICIPIO DE QUEVEDO PREDIOS', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE QUEVEDO TASAS', 'MSP', 'MUNICIPIO DE QUEVEDO TASAS', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE SAMBORONDON - VARIOS', 'MSP', 'MUNICIPIO DE SAMBORONDON', 'servicio', 'fija', 0.1000),
  ('MSP - MUNICIPIO DE SUCRE - VARIOS', 'MSP', 'MUNICIPIO DE SUCRE', 'servicio', 'fija', 0.1700),
  ('MSP - MUNICIPIOS - CUENCA - PREDIOS', 'MSP', 'MUNICIPIOS', 'servicio', 'fija', 0.1500),
  ('MSP - MUNICIPIOS - MEJIA', 'MSP', 'MUNICIPIOS', 'servicio', 'fija', 0.1100),
  ('MSP - PAGOS - AAASA CORPORATION', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - AFP GENESIS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - ARCSA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - ASSA AUTOMOTORES DE LA SIERRA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - AUTODIDACTA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - CERTERO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - CIRQUIMAX TECHNOLOGY ELECTRONICS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - CLUB GRAL AEROTECNICOS FAE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - CMS SERVICIOS ARQUITECTONICOS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - COBRANZA PAYROLL SA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - COBRANZA SERVICOBRANZAS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - COBRANZA SMARTECHSA SIN BASE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - COLEGIO DE ARQUITECTOS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - COMSATEL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - CONEXIONFAST', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - CONSTRUBENTHO CONSTRUCCIONES', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - CORP GUTENBERG SCHULE GUTSCHULE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - DIST FARM ECU DIFARE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - ECUAQUIMICA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - ECUAQUIMICA .', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - EDIFICIO CITY SUITES', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - EMGIRS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - FARCOMED', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FERREMUNDO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MSP - PAGOS - FERTISA AGIF', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - FESTHO INMOBILIARIA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FICHA MEDICA ASPIRANTES DE TRANSITO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - FIDEVAL FIDEICOMISO ACQUA SHOPS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FIDEICOMISO MIDTOWN 200', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FIDEICOMISO PLAZA SOHO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO ALIADO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO FIXED90', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO FLEXIBLE3060', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO IDEAL180', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO OBJETIVO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO PROGRAMADO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO REAL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDEVAL FONDO ADMINISTRADO VIVO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDUCIA FONDO ADM ACUMULACION', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDUCIA FONDO ADM PRODUCTIVO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDUCIA FONDO ADM RENTA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDUCIA FONDO ADM REPO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FIDUCIA FONDO OPORTUNIDAD', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FRANEMMA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FUNDACION ESPOIR', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - FUNDACION IDENTIDAD NACIONAL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - GADERE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - GATEHILL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - GESTIONA GTX', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - GRUPO INTERCOM TECHSMART', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - HAPPYCEL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - HAPPYPAY', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - HINO DEl ECUADOR', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - IGLESIA DE JESUCRISTO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - INSTTAMEDICAL SAS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - INTELCOBRO SA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - INTERNATIONAL HOUSE GUAYAQUIL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - JELOU POCKET', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - JUNTA BENEFICENCIA GUAYAQUIL EXEQUIALES', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - LAAR CIA LTDA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - LIBERTY SEGUROS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - LUDERQUIM', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - MAGDU', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - MAPFRE ECUADOR COMPANIA DE SEGUROS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - MEDIKEN MEDICINA INTEGRAL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - MEGATEL EC', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - MUEBLES EL BOSQUE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - NIKAMAR', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - NIKASTRANS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - NORWEGIAN REFUGEE COUNCIL NRC', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - PAGO LIQUIDACIONES EFECTIVO SALUD', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - PAYMON COBRANZA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - PAYMON RECARGAS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - PEPSICO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - PEPSICO ALIMENTOS ECUADOR', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - QUALA ECUADOR S.A. EN LINEA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - REGISTRO CIVIL CEDULA Y PASAPORTE PA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANT SAMBORONDON Y DURAN', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL AMBATO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL CUENCA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL ESMERALDAS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL GUAYAQUIL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL IBARRA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL MACHALA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL PORTOVIEJO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO MERCANTIL QUITO', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - REGISTRO PROPIEDAD DE GUAYAQUIL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - REGISTRO PROPIEDAD DE MACHALA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - REYLACTEOS CL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - ROL CMS SERVICIOS ARQUITECTONICOS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - ROL GSYPRO CIA LTDA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - ROL IMPORMEGATEX', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - ROL NORWEGIAN REFUGEE COUNCIL NRC', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SAINET - INTERNET', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SENAE - SERVICIO NACIONAL DE ADUANA DEL ECUADOR', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SITERTL CIA LTDA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SOCIEDAD CIVIL COLECTIVA MYL', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SOLDMER', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SOLINTEL SA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - SURTAX', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - SWEADEN SEGUROS', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - TELECONSULTA METRORED', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - TERCON', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - TIPTI', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - TRANSOCEANICA LOGISTICS TCLOG SA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - VILLA PLUS CONSTRUCTORA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1000),
  ('MSP - PAGOS - WERLEARNING SA', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PAGOS - WINGSMOBILE', 'MSP', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MSP - PARQUESANTO DEL ECUADOR PQE', 'MSP', 'PARQUESANTO DEL ECUADOR PQE', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - ACCESSNET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - CABLE FAMILIA (HC Global)', 'MSP', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MSP - PLANES - CABLE HOGAR', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - CABLE HOGAR MANABI NEOGIS - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - ECUANET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - FIBER STORE - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - FIBRAMAX ELIANA MOROCHO - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - FIBRAMAX-GEDATECU INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - FIBRATELECOM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - HEY IN PLANET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - HUGHESNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MSP - PLANES - IRONNET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - KOLVECH TELECOMVAS - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - MASNET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - MAXXNET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - ONETELECOM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - ONFIBER INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - OPTICOM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - ROCKNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - SPEEDYCOM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - SURNET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - TERRANET - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - UNIVISA', 'MSP', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MSP - PLANES - VELOCITY - KLIX - LOJASYSTEM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - PLANES - WIFITELECOM - INTERNET', 'MSP', 'PLANES', 'servicio', 'fija', 0.1000),
  ('MSP - SRI - IMPUESTOS CEP', 'MSP', 'SRI', 'servicio', 'fija', 0.1000),
  ('MSP - SRI - MATRICULACION - TRANSFERENCIA DOMINIO', 'MSP', 'SRI', 'servicio', 'fija', 0.1000),
  ('MSP - SRI - MATRICULACION AJUSTE', 'MSP', 'SRI', 'servicio', 'fija', 0.1000),
  ('MSP - SRI - MATRICULACION VEHICULAR', 'MSP', 'SRI', 'servicio', 'fija', 0.1700),
  ('MSP - SRI - RISE', 'MSP', 'SRI', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - ANDALUCIA', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - BANCO COMERCIAL MANABI', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - BANCO DE LOJA', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - BCO SOLIDARIO - ALÍA', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - COOPERATIVA TULCAN', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - PACIFICARD VISA y MC', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TARJETA DE CREDITO - VISA BGR', 'MSP', 'TARJETA DE CREDITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - ANT - CITACIONES', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1400),
  ('MSP - TRANSITO - ANT - PAGO SERVICIOS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - ATD - CITACIONES DURAN', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - ATD RECAUDACION DURAN', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - ATM CENTRO GUAYAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO COBRANZA CENTRO GUAYAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO COBRANZA JAMA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO COBRANZA SAN VICENTE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO MOBILITY DURAN', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO MOBILITY STO DOMINGO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - CONSORCIO MOBILITY-DINAMICA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MSP - TRANSITO - CTE - COMISION DE TRANSITO ECUADOR.', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - EMPRESA DE TRANSITO PASAJE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MSP - TRANSITO - EPMTG - ATM - CITACIONES', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - EPMTG - ATM - REVISION VEHICULAR GUAYAQUIL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - EPMTG - ATM - SOLICITUD', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - FOTOMULTAS MILAGRO EMOVIM', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - FOTOMULTAS QUEVIAL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - GAD PICHINCHA - PAGO FONDO VIAL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - GAD PICHINCHA FONDO MEJORAMIENTO VIAL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - INFRACCIONES MOVILIDAD DE MANTA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MATRICULACION MOVILIDAD DE MANTA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVIL DEL NORTE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MSP - TRANSITO - MOVILIDAD DE BALZAR', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE BUCAY', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE CAYAMBE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MSP - TRANSITO - MOVILIDAD DE CHONE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE DAULE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE FLAVIO ALFARO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE JAMA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE JUJAN', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE JUNIN', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE LATACUNGA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE MACHALA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE MONTECRISTI', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE NARANJAL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE OÑA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE PEDERNALES', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE PLAYAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE PUERTO LOPEZ', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE QUIJOS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE SALINAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE SAN VICENTE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE SANTA ELENA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DE YAGUACHI', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD DEL EMPALME', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD JOYA DE LOS SACHAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD LA CONCORDIA', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD MILAGRO - EMOVIM - ACT', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MOVILIDAD PORTOVIAL', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MULTAS DE TRANSITO ESMERALDAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - MULTAS TRANSITO STO DOMINGO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MSP - TRANSITO - MUNICIPIO DE CAYAMBE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - PEAJE RUMIÑAHUI POST-PAGO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - PEAJE RUMIÑAHUI RECARGAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MSP - TRANSITO - RECARGAS PANAVIAL TELEPASS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - REVISION VEHICULAR ARCONADA - MONTECRISTI', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - REVISION VEHICULAR MILAGRO EMOVIM', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - REVISION VEHICULAR PAUTE', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('MSP - TRANSITO - REVISION VEHICULAR QUITO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MSP - TRANSITO - TRANSVIAL DE BABAHOYO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MSP - TRANSITO - TUNEL GUAYASAMIN POST-PAGO', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MSP - TRANSITO - TUNEL GUAYASAMIN RECARGAS', 'MSP', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - AGUA DE MILAGRO - EPAMIL - ABONO 1', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - AGUAPEN SANTA ELENA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - AGUAS MACHALA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - AMAGUA - SAMBORONDON', 'MTD', 'AGUA', 'servicio', 'fija', 0.1400),
  ('MTD - AGUA - ANTONIO ANTE - ATUNTAQUI', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - CHONE', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAAP - QUITO - ABONO 1', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAPA AZOGUES', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAPA CAYAMBE', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAPA DAULE', 'MTD', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - EMAPA LAGO AGRIO', 'MTD', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - EMAPA-AMBATO - ABONO 1', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAPA-I IBARRA - ABONO 1', 'MTD', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - EMAPA-MEJIA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - EMAPAG-GUARANDA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMAPSE ESMERALDAS', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMASA - AGUAS DE PEDRO MONCAYO - ABONO 1', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMMAP (CANTON BOLIVAR-JUNIN-SAN VICENTE-SUCRE-TOSAGUA)', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EMRAPAH ARENILLAS', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - EMRAPAH HUAQUILLAS', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - EMSABA BABAHOYO', 'MTD', 'AGUA', 'servicio', 'fija', 0.1000),
  ('MTD - AGUA - EPMAPA PUERTO LOPEZ', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - EPMAPA SANTO DOMINGO', 'MTD', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - ETAPA AZUAY', 'MTD', 'AGUA', 'servicio', 'fija', 0.1300),
  ('MTD - AGUA - HIDRO PLAYAS', 'MTD', 'AGUA', 'servicio', 'fija', 0.1500),
  ('MTD - AGUA - INTERAGUA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - JARAMIJO- HIDROJAR', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - JIPIJAPA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - LATACUNGA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - MONTECRISTI', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - MUNICIPIO RIOBAMBA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - OTAVALO', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUA - PEDERNALES - EPMAPA-PED', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - PUJILI- EPAPAP', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - QUEVEDO- EMAPAQ', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - ROCAFUERTE - EPAPAR', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - SANTA ISABEL', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - SANTA ROSA', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - SUCUA-EPMAPAF-S', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - SUCUMBIOS', 'MTD', 'AGUA', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - URCUQUI', 'MTD', 'AGUA', 'servicio', 'fija', 0.1100),
  ('MTD - AGUAS PASAJE - AGUAPAS', 'MTD', 'AGUAS PASAJE', 'servicio', 'fija', 0.1700),
  ('MTD - AGUA - BUENA FE -EMAPSA BF', 'MTD', 'AGUA - BUENA FE -EMAPSA BF', 'servicio', 'fija', 0.1700),
  ('MTD - ALICUOTAS - URBANIZACION VERANDA', 'MTD', 'ALICUOTAS', 'servicio', 'fija', 0.1500),
  ('MTD - ATM - GUAYAQUIL - PAGO DE CITACIONES', 'MTD', 'ATM', 'servicio', 'fija', 0.1400),
  ('MTD - ATM - GUAYAQUIL - PAGO DE TARIFAS POR NÚMERO DE TRAMITE', 'MTD', 'ATM', 'servicio', 'fija', 0.1400),
  ('MTD - ATM - GUAYAQUIL - RENOVACIÓN DE PERMISO CIRCULACIÓN VEHICULAR', 'MTD', 'ATM', 'servicio', 'fija', 0.1400),
  ('MTD - CATALOGO - AZZORTI', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - BELCORP', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - HERBALIFE', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - L-EUDINE', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - LD ELEDE ECUADOR VENTA CATALOGO', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - LEONISA', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - MIO', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - NATURA AVON', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - NIVI', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - OMNILIFE', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - ORIFLAME', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CATALOGO - RELEVANCE', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - REVOLUSS', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - RIHE -MARTTELOCORP', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1700),
  ('MTD - CATALOGO - ZERMAT S.A.', 'MTD', 'CATALOGO', 'servicio', 'fija', 0.1300),
  ('MTD - CLARO - PLAN POSTPAGO', 'MTD', 'CLARO', 'servicio', 'fija', 0.1700),
  ('MTD - CLARO - PLANES DE CARTERA VENCIDA', 'MTD', 'CLARO', 'servicio', 'fija', 0.1500),
  ('MTD - CLARO - PLANES TV SATELITAL', 'MTD', 'CLARO', 'servicio', 'fija', 0.1700),
  ('MTD - CLARO - TELEFONIA FIJA', 'MTD', 'CLARO', 'servicio', 'fija', 0.1700),
  ('MTD - CNT - INTERNET', 'MTD', 'CNT', 'servicio', 'fija', 0.1700),
  ('MTD - CNT - TELEFONIA FIJA - ABONO 1', 'MTD', 'CNT', 'servicio', 'fija', 0.1700),
  ('MTD - CNT - TV PAGADA', 'MTD', 'CNT', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ALMACENES ESPAÑA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ALMACENES JAPÓN', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ALMACENES JAPÓN MOTOS', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ALMACENES ORVE HOGAR', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ARTEFACTA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CARTERA VENCIDA - ARTEFACTA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CARTERA VENCIDA - COGESCORP', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CARTERA VENCIDA - COLLSERV', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CARTERA VENCIDA - CTH', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CARTERA VENCIDA - GABELLI', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - CARTERA VENCIDA - GRUPO FINANCIERO DIAL', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - CHIMASA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - COBRAMAS', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - CONSORCIO GANE', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - COOP COAC ANDINA LTDA.', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - CREDACART', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - CREDIGESTION', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - CREDITOS ECONOMICOS', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - D-PRATI', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ECUASUEÑA S.A.', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - ETAFASHION', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - FINSOLRED', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - FUNDACION ESPOIR', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - GOOD PRICE', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - GRAN HOGAR', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - HAPPY', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - INSOTEC TU', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - LATICOBSA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - MARCIMEX', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - MASKANA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - MOTDIS', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - PORTCOLL HYUNDAI', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - CREDITO - PYCCA', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - REBAJA MODA RM', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - RECOVER', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1700),
  ('MTD - CREDITO - SERVICOBRANZAS', 'MTD', 'CREDITO', 'servicio', 'fija', 0.1300),
  ('MTD - ETAPA - TELEFONIA FIJA', 'MTD', 'ETAPA', 'servicio', 'fija', 0.1300),
  ('MTD - IESS', 'MTD', 'IESS', 'servicio', 'fija', 0.1700),
  ('MTD - INTERAGUA CUPONES', 'MTD', 'INTERAGUA CUPONES', 'servicio', 'fija', 0.1700),
  ('MTD - JARDINES DE ESPERANZA', 'MTD', 'JARDINES DE ESPERANZA', 'servicio', 'fija', 0.1500),
  ('MTD - LUZ - CENTROSUR AZUAY - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - BOLIVAR - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - EL ORO - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - ELECTRICA GUAYAQUIL - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - ESMERALDAS - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - GUAYAS LOS RIOS - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - LOS RIOS - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - MANABI - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - MILAGRO - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - BOLIVAR', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - EL ORO', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - ELECTRICA GUAYAQUIL', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - ESMERALDAS', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - GUAYAS LOS RIOS', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - LOS RIOS', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - MANABI', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - MILAGRO', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - SANTA ELENA', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - SANTO DOMINGO', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - PREPAGO - SUCUMBIOS', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - SANTA ELENA - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - STO. DOMINGO - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - CNEL - SUCUMBIOS - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - EEQ QUITO - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - EERSA - LUZ RIOBAMBA', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - EERSSA LOJA', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - ELECTRICA GALÁPAGOS', 'MTD', 'LUZ', 'servicio', 'fija', 0.1700),
  ('MTD - LUZ - EMELNORTE (IMBABURA-CARCHI-CAYAMBE) - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1400),
  ('MTD - LUZ - MEER - ELECTRICA AZOGUES - ABONO 1', 'MTD', 'LUZ', 'servicio', 'fija', 0.1200),
  ('MTD - LUZ COTOPAXI -ELEPCO', 'MTD', 'LUZ COTOPAXI -ELEPCO', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - ANAI', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - CENEST HARVARD', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - COLEGIO ALMIRANTE NELSON', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - COLEGIO CRISTOBAL COLÓN', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - COLEGIO DOMINGO COMÍN', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - COLEGIO DOMINGO SAVIO', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - COPEI', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - IST BOLIVARIANO', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - KOE', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - TECNOLÓGICO ARGOS', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - U. E. PDTE. CARLOS JULIO AROSEMENA UNEPAT', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - U. EDUCATIVA PAUL RIVET', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1500),
  ('MTD - MATRICULAS Y PENSIONES - UNIVERSIDAD INDOAMERICA', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - UNIVERSIDAD LAICA VICENTE ROCAFUERTE', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MATRICULAS Y PENSIONES - UTEL - SCALA HIGHER EDUCATION', 'MTD', 'MATRICULAS Y PENSIONES', 'servicio', 'fija', 0.1700),
  ('MTD - MOVISTAR - PLAN POSTPAGO - VALOR MAYOR A 10 USD', 'MTD', 'MOVISTAR', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIO SANTO DOMINGO - PREDIOS', 'MTD', 'MUNICIO SANTO DOMINGO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO - GAD CUENCA - PREDIOS - CEDULA', 'MTD', 'MUNICIPIO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO - GAD CUENCA - PREDIOS - CLAVE CATASTRAL', 'MTD', 'MUNICIPIO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE ANTONIO ANTE - PREDIOS', 'MTD', 'MUNICIPIO DE ANTONIO ANTE', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE BABAHOYO - PREDIOS', 'MTD', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE BAÑOS - PREDIOS', 'MTD', 'MUNICIPIO DE BAÑOS', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE BOLIVAR - PREDIOS', 'MTD', 'MUNICIPIO DE BOLIVAR', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE BUENA FE - PREDIOS', 'MTD', 'MUNICIPIO DE BUENA FE', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE CAYAMBE - PREDIOS', 'MTD', 'MUNICIPIO DE CAYAMBE', 'servicio', 'fija', 0.1000),
  ('MTD - MUNICIPIO DE CAÑAR - PREDIOS', 'MTD', 'MUNICIPIO DE CAÑAR', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE CHONE - PREDIOS', 'MTD', 'MUNICIPIO DE CHONE', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE COTACACHI - VARIOS (AGUA - IMPUESTOS)', 'MTD', 'MUNICIPIO DE COTACACHI', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE GUAYAQUIL - IMPUESTO MERCADOS', 'MTD', 'MUNICIPIO DE GUAYAQUIL', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE GUAYAQUIL - PAGOS CEP', 'MTD', 'MUNICIPIO DE GUAYAQUIL', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE IBARRA - PREDIOS', 'MTD', 'MUNICIPIO DE IBARRA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE LIBERTAD - PREDIOS', 'MTD', 'MUNICIPIO DE LIBERTAD', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE LOJA - PREDIOS', 'MTD', 'MUNICIPIO DE LOJA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE MACHALA - PREDIOS', 'MTD', 'MUNICIPIO DE MACHALA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE MONTUFAR - PREDIOS', 'MTD', 'MUNICIPIO DE MONTUFAR', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE MORONA - PREDIOS', 'MTD', 'MUNICIPIO DE MORONA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE OTAVALO - PREDIOS', 'MTD', 'MUNICIPIO DE OTAVALO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE PANGUA - PREDIOS', 'MTD', 'MUNICIPIO DE PANGUA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE PELILEO - PREDIOS', 'MTD', 'MUNICIPIO DE PELILEO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE PILLARO - PREDIOS', 'MTD', 'MUNICIPIO DE PILLARO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE PORTOVIEJO - PREDIOS', 'MTD', 'MUNICIPIO DE PORTOVIEJO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE QUITO - PREDIO', 'MTD', 'MUNICIPIO DE QUITO', 'servicio', 'fija', 0.1400),
  ('MTD - MUNICIPIO DE RUMIÑAHUI - PREDIOS', 'MTD', 'MUNICIPIO DE RUMIÑAHUI', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE SANTA ISABEL - PREDIOS', 'MTD', 'MUNICIPIO DE SANTA ISABEL', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE SARAGURO - AGUA E IMPUESTOS', 'MTD', 'MUNICIPIO DE SARAGURO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE SUCRE - PREDIOS', 'MTD', 'MUNICIPIO DE SUCRE', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE SUCUMBIOS - PREDIOS', 'MTD', 'MUNICIPIO DE SUCUMBIOS', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE TENA - PREDIOS', 'MTD', 'MUNICIPIO DE TENA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DE TULCAN - PREDIOS', 'MTD', 'MUNICIPIO DE TULCAN', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO DURAN - PREDIOS', 'MTD', 'MUNICIPIO DURAN', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO GAD AMBATO (BCE)', 'MTD', 'MUNICIPIO GAD AMBATO (BCE)', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO GAD ATACAMES - PREDIOS', 'MTD', 'MUNICIPIO GAD ATACAMES', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO GAD DAULE - PREDIOS', 'MTD', 'MUNICIPIO GAD DAULE', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO GUAYAQUIL - EMP PUBLICA MUNICIPAL DE VIVIENDA', 'MTD', 'MUNICIPIO GUAYAQUIL', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO MILAGRO - PREDIOS', 'MTD', 'MUNICIPIO MILAGRO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO PIMAMPIRO', 'MTD', 'MUNICIPIO PIMAMPIRO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO QUEVEDO - VARIOS', 'MTD', 'MUNICIPIO QUEVEDO', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIO RIOBAMBA - IMPUESTOS', 'MTD', 'MUNICIPIO RIOBAMBA', 'servicio', 'fija', 0.1700),
  ('MTD - MUNICIPIOS - MANTA', 'MTD', 'MUNICIPIOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - ACTIVAPAY', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - ADEATEL', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - ALMACENES JAHER', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - AUTOCLUB', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - BOMBEROS MILAGRO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - BOMBEROS PORTOVIEJO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - CARSYNC', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - CNE (CONSEJO NACIONAL ELECTORAL) - MULTAS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - CORPORACION CR', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - CRECOSCORP CREDITOS ECONOMICOS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - DURAGAS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - ELECTROEXITO-PORTCOLL S.A.', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - EQPAY', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - FEDERACINN DEPORTIVA DEL AZUAY', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - FEDERACIÓN DEPORTIVA DEL GUAYAS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - FUTGOLAZO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - GAIN PHONE', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - HEY', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - HUNTER', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - INTELCOBRO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - JARDINES DE DURAN', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - JARDINES DE MANABI', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - JARDINES DE QUEVEDO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - JUEGA EN LINEA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - KUSHKI PAGOS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - MONNETPAYMENTS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - MOTOINDUSTRIAS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - MOVILIZA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - MUNDO BOLETOS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - NETWORK COMMUNICATIONS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAGAR ES FÁCIL', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAGO 46', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAGOSEGURO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAGUE YA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PARQUESANTO DEL ECUADOR', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAY JOY', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAYCASH', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PAYMENTLATAM', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PEAJE MANABI VIAL', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - PRONTOPAGA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - QRC SOLUTIONS', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - REGISTRO CIVIL CEDULA Y PASAPORTE', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - REGISTRO DE LA PROPIEDAD', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - REGISTRO MERCANTIL CUENCA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - REGISTRO MERCANTIL SANTO DOMINGO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - REGISTRO PROPIEDAD OTAVALO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - ROLAND -LILI PINK', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SAMSUNG STORE', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SECURITY DATA', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SERVICIOS POSTALES', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SERVINACIONALES', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SOLUCIONES EL RECUERDO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - SUSCRIPTORES DIARIO EXPRESO', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - TASA DE RECOLECCIÓN DE BASURA GUAYAQUIL', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - TELMODER', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - TICKETS - MAS PRODUCCIONES', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS - TREBALIA', 'MTD', 'PAGOS', 'servicio', 'porcentual', 1.0000),
  ('MTD - PAGOS - TRIPCAR', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS - YIGA 5', 'MTD', 'PAGOS', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS EN LINEA - GUAYAQUIL SPORT CLUB', 'MTD', 'PAGOS EN LINEA', 'servicio', 'fija', 0.1700),
  ('MTD - PAGOS EN LINEA - MUEBLES EL BOSQUE S.A.', 'MTD', 'PAGOS EN LINEA', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS EN LINEA - PAGO EFECTIVO', 'MTD', 'PAGOS EN LINEA', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS EN LINEA - PARQUE DE LA PAZ', 'MTD', 'PAGOS EN LINEA', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS EN LINEA - SOCIOS BARCELONA', 'MTD', 'PAGOS EN LINEA', 'servicio', 'fija', 0.1500),
  ('MTD - PAGOS EN LINEA- PIA', 'MTD', 'PAGOS EN LINEA- PIA', 'servicio', 'fija', 0.1500),
  ('MTD - PLANES -  TV ORO PORTOVELO - ZARUMA - INTERNET - TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ALFANET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ALFATV CABLE', 'MTD', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MTD - PLANES - BLUENET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE FAMILIA', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE FUTURO', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE HOGAR', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE HOGAR - INTERNET Y TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE MAGICO', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLE MAGICO MORONA SANTIAGO - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CABLESPEED', 'MTD', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MTD - PLANES - CNT POSTPAGO', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - COPERCONET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - CORPECONET VELOCITY - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - COSTACOMTV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - DE UNA TVNET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - DIRECTV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1400),
  ('MTD - PLANES - ETAPA', 'MTD', 'PLANES', 'servicio', 'fija', 0.1300),
  ('MTD - PLANES - FASTNETT', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - FIBERGO INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - FIBRALINK - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - FIBRAMAX - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - FIBRATELECOM - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - FORED - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - GIGATEL - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - HCNET INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - INTERCOM - OTRAS CIUDADES - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - INTERCOM INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - INTERDATOS (INTERNET BABHOYO-JUJAN-BABA)', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - INTERNET FIBRA LATAM', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - INTERNET MR', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - KATARI TELECOM - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - LA RED (INTERNT Y TVCABLE ESMERALDAS)', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - LINKOTEL TELEFONIA', 'MTD', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MTD - PLANES - MASNET (INTERNET SANTA ANA-24 DE MAYO-PORTOVIEJO)', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - MAXITEL INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - MAXXNET -INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - MEGATEL - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - NEOGISP - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - NEONET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - NETLIFE', 'MTD', 'PLANES', 'servicio', 'fija', 0.1400),
  ('MTD - PLANES - NETTPLUS - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - NITROHOME - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - OCEANNET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ONE - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ONFIBER - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - OPTICOM', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - PUNTONET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1400),
  ('MTD - PLANES - RADIALNET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - RAPINET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SAITEL - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1500),
  ('MTD - PLANES - SIMANTEC - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SINTELCOM INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SKYNET (INTERNET DURAN-YAGUACHI)', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SONIC NET - INTERNET - TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SPEDDY INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - SUMPA INTERNET Y TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TECGLO TECNOLOGÍA GLOBAL INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TELECOMVÁS', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TRANSMEDICAL', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TVCABLE', 'MTD', 'PLANES', 'servicio', 'fija', 0.1200),
  ('MTD - PLANES - TVNET INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TVORO HUAQUILLAS - INTERNET - TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TVORO MACHALA - INTERNET - TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - TVPACÍFICO INTERNET Y TV', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ULTRALINK - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - VALLENET - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - VELOCITY', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - VELOCITY LOJA - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - VISIÓN MÁGICA', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - WIFITELECOM - INTERNET', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES - ZAPPING', 'MTD', 'PLANES', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES -ECUANET - INTERNET', 'MTD', 'PLANES -ECUANET', 'servicio', 'fija', 0.1700),
  ('MTD - PLANES DE COMPRAS - CASA PLAN MOTOR PLAN', 'MTD', 'PLANES DE COMPRAS', 'servicio', 'fija', 0.1500),
  ('MTD - PRONOSTICOS - ASTROBET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - BET593', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - BETCRIS', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - DATABET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - DORADOBET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - ECUABET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - LATRIBET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - PRONOSTICOS - MAS1X2', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 0.1700),
  ('MTD - PRONOSTICOS - SPORTBET', 'MTD', 'PRONOSTICOS', 'juego', 'porcentual', 1.0000),
  ('MTD - SRI - IMPUESTOS CEP', 'MTD', 'SRI', 'servicio', 'fija', 0.1700),
  ('MTD - SUSCRIPTORES - DIARIO EXPRESO', 'MTD', 'SUSCRIPTORES', 'servicio', 'fija', 0.1500),
  ('MTD - TRANSITO - CONSORCIO COBRANZA DURAN – ATD - CITACIONES', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - CTE COMISIÓN DE TRANSITO', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1400),
  ('MTD - TRANSITO - CVIALCO - PEAJE VIA A LA COSTA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - EMOT - ATD DURAN CITACIONES', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - EMOT - ATD DURAN ORDEN DE PAGO - MATRICULACION Y RETENCION VEHICULAR', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - EMOV', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1500),
  ('MTD - TRANSITO - EMOV TRANSITO CUENCA (FO)', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - EPMC-PASTAZA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - GADP MANABÍ - CITACIONES Y MATRICULACION', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - GADP PICHINCHA PEAJE', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - MOVILIDAD COTOPAXI PREFECTURA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - MOVILIDAD LATACUNGA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - MOVILIDAD LOS RIOS-PREFECTURA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - PEAJES - TAG EXPRESS BILLETERA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - PEAJES - TAG EXPRESS PREPAGO', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - RECAUDACION ORDENES DE PAGO EMOVIM - IMPUESTOS Y TASAS', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - RTV DURAN - REVISION TECNICA VEHICULAR', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('MTD - TRANSITO - TASA DE CONTRIBUCION VIAL GAD PASTAZA', 'MTD', 'TRANSITO', 'servicio', 'fija', 0.1700),
  ('TRINITY - AGUA - AZOQUES', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - LOJA', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - MUNICIPIO PANGUA', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - PIMAMPIRO', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - RIOBAMBA', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - SAN MIGUEL DE BOLIVAR', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - AGUA - VENTANAS', 'TRINITY', 'AGUA', 'servicio', 'fija', 0.1000),
  ('TRINITY - COLOMBIA - AVANTEL', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - CELLVOZ', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - CLARO', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - DIRECTV', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - ETB', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - FLASH MOBILE', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - MOVIL EXITO', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - MOVISTAR', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - TIGO', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - COLOMBIA - VIRGIN', 'TRINITY', 'COLOMBIA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - CONSEJO JUDICATURA - PENSION ALIMENTICIA EMPRESAS', 'TRINITY', 'CONSEJO JUDICATURA', 'servicio', 'fija', 0.1000),
  ('TRINITY - CONSEJO JUDICATURA - PENSION ALIMENTICIA PERSONAS', 'TRINITY', 'CONSEJO JUDICATURA', 'servicio', 'fija', 0.1000),
  ('TRINITY - CUBA - CUBACEL', 'TRINITY', 'CUBA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - FREE FIRE', 'TRINITY', 'FREE FIRE', 'servicio', 'fija', 0.1000),
  ('TRINITY - MOBILE LEGENDS', 'TRINITY', 'MOBILE LEGENDS', 'servicio', 'fija', 0.0000),
  ('TRINITY - MUNICIPIO - SAN MIGUEL - PATENTE', 'TRINITY', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO - SAN MIGUEL - PREDIO RURAL', 'TRINITY', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO - SAN MIGUEL - PREDIO URBANO', 'TRINITY', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO - SAN MIGUEL - RECOLECCION BASURA', 'TRINITY', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO - SAN MIGUEL - VARIOS', 'TRINITY', 'MUNICIPIO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE AMBATO - PREDIOS', 'TRINITY', 'MUNICIPIO DE AMBATO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - ACTIVOS TOTALES', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - ALCABALAS', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - CONTRIB. MEJORAS', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - PATENTE', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - PREDIO RURAL', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - PREDIO URBANO', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - RECOL. BASURA', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE BABAHOYO - VARIOS', 'TRINITY', 'MUNICIPIO DE BABAHOYO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE CAYAMBE - PREDIO RURAL', 'TRINITY', 'MUNICIPIO DE CAYAMBE', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE CAYAMBE - PREDIO URBANO', 'TRINITY', 'MUNICIPIO DE CAYAMBE', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE GUARANDA - PREDIO RURAL', 'TRINITY', 'MUNICIPIO DE GUARANDA', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE GUARANDA- PREDIO URBANO', 'TRINITY', 'MUNICIPIO DE GUARANDA- PREDIO URBANO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE QUEVEDO - PREDIOS', 'TRINITY', 'MUNICIPIO DE QUEVEDO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE RIOBAMBA - PREDIOS', 'TRINITY', 'MUNICIPIO DE RIOBAMBA', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE RUMIÑAHUI - PREDIOS', 'TRINITY', 'MUNICIPIO DE RUMIÑAHUI', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE STO. DOMINGO - PREDIOS', 'TRINITY', 'MUNICIPIO DE STO. DOMINGO', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE URCUQUI - PREDIO RURAL', 'TRINITY', 'MUNICIPIO DE URCUQUI', 'servicio', 'fija', 0.1000),
  ('TRINITY - MUNICIPIO DE URCUQUI - PREDIO URBANO', 'TRINITY', 'MUNICIPIO DE URCUQUI', 'servicio', 'fija', 0.1000),
  ('TRINITY - PLANES - IMBACABLE', 'TRINITY', 'PLANES', 'servicio', 'fija', 0.1000),
  ('TRINITY - PLANES - PLUS SERVICIOS TECNOLOGICOS', 'TRINITY', 'PLANES', 'servicio', 'fija', 0.1000),
  ('TRINITY - PRODUBANCO - CONSULTA SALDO DE CUENTA', 'TRINITY', 'PRODUBANCO', 'servicio', 'fija', 0.1000),
  ('TRINITY - PRODUBANCO - DEPOSITOS', 'TRINITY', 'PRODUBANCO', 'servicio', 'fija', 0.1000),
  ('TRINITY - PRODUBANCO - RETIROS DE CUENTA', 'TRINITY', 'PRODUBANCO', 'servicio', 'fija', 0.1000),
  ('TRINITY - PRODUBANCO - RETIROS DE CUENTA - OTP PRE GENERADO', 'TRINITY', 'PRODUBANCO', 'servicio', 'fija', 0.1000),
  ('TRINITY - PRODUBANCO - TARJETA DE CREDITO - VISA - MASTERCARD', 'TRINITY', 'PRODUBANCO', 'servicio', 'fija', 0.1000),
  ('TRINITY - ROBLOX', 'TRINITY', 'ROBLOX', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSITO - COTOPAXI - IMP. RODAJE', 'TRINITY', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSITO - LOJA', 'TRINITY', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSITO - MOVILIDAD LOS RIOS - LIVIANO', 'TRINITY', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSITO - MOVILIDAD LOS RIOS - MOTOCICLETA', 'TRINITY', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSITO - MOVILIDAD LOS RIOS - OTROS', 'TRINITY', 'TRANSITO', 'servicio', 'fija', 0.1000),
  ('TRINITY - TRANSPORTE - GUAYAQUIL - LA GUAYACA', 'TRINITY', 'TRANSPORTE', 'servicio', 'porcentual', 0.5000),
  ('TRINITY - VENEZUELA - DIGITEL', 'TRINITY', 'VENEZUELA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - VENEZUELA - MOVILNET', 'TRINITY', 'VENEZUELA', 'recarga', 'porcentual', 5.0000),
  ('TRINITY - VENEZUELA - MOVISTAR', 'TRINITY', 'VENEZUELA', 'recarga', 'porcentual', 5.0000)
on conflict (nombre) do update set
  comision_tipo = excluded.comision_tipo,
  comision_valor = excluded.comision_valor,
  tipo = excluded.tipo;
